[tool.poetry]
name = "balance-api"
version = "0.1.0"
description = ""
authors = ["Juliano Vidal <juliano.vidal@gmail.com>"]
readme = "README.md"
packages = [{include = "balance_api"}]

[tool.poetry.dependencies]
python = "^3.10"
connexion = "^2.14.1"
alembic = "^1.8.1"
flask-compress = "^1.13"
flask-cors = "^3.0.10"
flask-sqlalchemy = "^3.0.2"
psycopg2-binary = "^2.9.5"
pyjwt = {extras = ["crypto"], version = "^2.6.0"}
backoff = "^2.2.1"
meza = "^0.46.0"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pytest = "^7.2.0"


[tool.poetry.group.production.dependencies]
uwsgi = "^2.0.21"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
