"""Create transactions table

Revision ID: 5b1cc7298dbe
Revises: df76125d06a9
Create Date: 2021-06-20 17:21:05.890349

"""

from alembic import op
from sqlalchemy import TEXT, Column, INTEGER, ForeignKey, Enum, DATE, FLOAT, DateTime
from sqlalchemy.engine.reflection import Inspector

from balance_api.models.transactions import Transaction, TransactionType

# revision identifiers, used by Alembic.
revision = '5b1cc7298dbe'
down_revision = 'df76125d06a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if Transaction.__tablename__ not in tables:
        op.create_table(
            Transaction.__tablename__,
            Column("id", INTEGER, primary_key=True, autoincrement=True),
            Column("date", DATE),
            Column("type", Enum(TransactionType)),
            Column("amount", FLOAT),
            Column("account_id", INTEGER, ForeignKey("accounts.id", onupdate="CASCADE", ondelete="CASCADE")),
            Column("description", TEXT),
            Column("tag_id", INTEGER, ForeignKey("tags.id", onupdate="CASCADE")),
            Column("created_at", DateTime, nullable=False),
            Column("updated_at", DateTime, nullable=False),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(Transaction.__tablename__)
    # ### end Alembic commands ###
