"""Create assets table

Revision ID: a4c1e7240a0c
Revises: 5b1cc7298dbe
Create Date: 2021-06-28 23:03:22.917344

"""
from alembic import op
from sqlalchemy import FLOAT
from sqlalchemy import TEXT, Column, DateTime
from sqlalchemy.engine.reflection import Inspector

from balance_api.data.models.assets import Asset

# revision identifiers, used by Alembic.
revision = "a4c1e7240a0c"
down_revision = "5b1cc7298dbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if Asset.__tablename__ not in tables:
        op.create_table(
            Asset.__tablename__,
            Column("isin", TEXT, primary_key=True),
            Column("description", TEXT),
            Column("currency", TEXT),
            Column("price", FLOAT),
            Column("created_at", DateTime, nullable=False),
            Column("updated_at", DateTime, nullable=False),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(Asset.__tablename__)
    # ### end Alembic commands ###
