"""Create assets and transaction asset table

Revision ID: a4c1e7240a0c
Revises: 5b1cc7298dbe
Create Date: 2021-06-28 23:03:22.917344

"""
from alembic import op
from sqlalchemy import TEXT, Column, FLOAT, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.engine.reflection import Inspector

from balance_api.models.assets import Asset
from balance_api.models.transaction_asset import TransactionAsset

# revision identifiers, used by Alembic.
revision = 'a4c1e7240a0c'
down_revision = '5b1cc7298dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if Asset.__tablename__ not in tables:
        op.create_table(
            Asset.__tablename__,
            Column("isin", TEXT, primary_key=True),
            Column("price", FLOAT),
            Column("created_at", DateTime, nullable=False),
            Column("updated_at", DateTime, nullable=False),
        )

    if TransactionAsset.__tablename__ not in tables:
        op.create_table(
            TransactionAsset.__tablename__,
            Column(
                "transaction_id",
                UUID(as_uuid=True),
                ForeignKey("transactions.id", onupdate="CASCADE", ondelete="CASCADE")
            ),
            Column(
                "asset_isin",
                TEXT,
                ForeignKey("assets.isin", onupdate="CASCADE", ondelete="CASCADE")
            ),
            Column("amount", FLOAT, nullable=False),
            Column("created_at", DateTime, nullable=False),
            Column("updated_at", DateTime, nullable=False),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(Asset.__tablename__)
    op.drop_table(TransactionAsset.__tablename__)
    # ### end Alembic commands ###
