"""Add currency to account

Revision ID: d964d0ccd9c6
Revises: a8c0c8235c5f
Create Date: 2021-08-28 11:09:28.920168

"""
from alembic import op
import sqlalchemy as sa

from balance_api.models import CurrencyType

# revision identifiers, used by Alembic.
revision = "d964d0ccd9c6"
down_revision = "a8c0c8235c5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE currencytype AS ENUM ('EUR', 'BRL');")
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.Enum(CurrencyType),
        ),
    )
    op.add_column(
        "accounts",
        sa.Column("currency", sa.Enum(CurrencyType)),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS currencytype;")
    op.drop_column("users", "currency")
    op.drop_column("accounts", "currency")
    # ### end Alembic commands ###
