"""Create tags

Revision ID: df76125d06a9
Revises: 0ce5b4e2f2cb
Create Date: 2021-06-20 17:03:08.874443

"""
from alembic import op
from sqlalchemy import TEXT, Column, INTEGER, ForeignKey, DateTime
from sqlalchemy.engine.reflection import Inspector

from balance_api.models.tags import Tag

# revision identifiers, used by Alembic.
revision = "df76125d06a9"
down_revision = "0ce5b4e2f2cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if Tag.__tablename__ not in tables:
        op.create_table(
            Tag.__tablename__,
            Column("id", INTEGER, primary_key=True, autoincrement=True),
            Column("value", TEXT),
            Column(
                "user_id",
                INTEGER,
                ForeignKey("users.id", onupdate="CASCADE", ondelete="CASCADE"),
            ),
            Column("created_at", DateTime, nullable=False),
            Column("updated_at", DateTime, nullable=False),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(Tag.__tablename__)
    # ### end Alembic commands ###
