name: Semantic Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # To create tags and releases
      id-token: write
      issues: write        # To post comments on issues/PRs
      pull-requests: write # To post comments on issues/PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Crucial: semantic-release needs the full git history to determine the version
          fetch-depth: 0

      - name: Run semantic-release
        uses: python-semantic-release/python-semantic-release@v10.1.0
        with:
          changelog: false
          commit: false
          tag: true