openapi: 3.0.0
info:
  title: Balance Application API
  description: |
    This API allows writing down marks on a Tic Tac Toe board
    and requesting the state of the board or of individual squares.
  version: 1.0.0

components:
  parameters:
    UserId:
      in: path
      name: user_id
      description: Unique User ID
      required: true
      schema:
        type: integer
        format: int32

    AccountId:
      in: path
      name: account_id
      description: Unique Account ID
      required: true
      schema:
        type: string
        format: uuid

    TransactionId:
      in: path
      name: transaction_id
      description: Unique Transaction ID
      required: true
      schema:
        type: string
        format: uuid

    AccountIdQuery:
      in: query
      name: account_id
      description: User account id
      required: false
      schema:
        type: string
        format: uuid

    PeriodType:
      in: query
      name: period_type
      description: Period Type
      required: false
      schema:
        type: string
        x-extensible-enum:
          - custom
          - last_month

    PeriodOffset:
      in: query
      name: period_offset
      description: Period Offset
      required: false
      schema:
        type: integer
        format: int32

    StartDate:
      in: query
      name: start_date
      description: Start Date
      required: false
      schema:
        type: string
        format: date-time

    EndDate:
      in: query
      name: end_date
      description: End Date
      required: false
      schema:
        type: string
        format: date-time

  schemas:
    User:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int32
          example: 1
          description: User id
        name:
          type: string
          nullable: true
          example: 'John Doe'
          description: The user name
        created_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was created
        updated_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was last modified/updated

    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "5cdd1623-3d0a-4a21-a6be-cd1463f566fb"
          description: account id
        alias:
          type: string
          nullable: true
          example: 'Santander'
          description: The account alias
        user_id:
          type: integer
          format: int32
          example: 1
          description: The user id
        type:
          type: string
          nullable: true
          x-extensible-enum:
            - CHECKING
            - SAVINGS
            - INVESTMENTS
            - OTHERS
          example: 'checking'
          description: The account type
        balance:
          type: number
          format: float
          example: 3.15
          description: The account balance
        created_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was created
        updated_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was last modified/updated

    Accounts:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'

    AccountTag:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: account id
        value:
          type: string
          nullable: true
          example: 'Miscellaneous'
          description: The account tag value
        account_id:
          type: integer
          example: 1
          description: The user account id
        created_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was created
        updated_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was last modified/updated

    AccountTags:
      type: object
      properties:
        tags:
          type: array
          items:
            $ref: '#/components/schemas/AccountTag'

    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "c88e96f6-24ae-49cd-8d6a-fa4fa753e17f"
          description: transaction id
        date:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26'
          description: The timestamp when the transaction was realized
        transaction_type:
          type: string
          nullable: true
          x-extensible-enum:
            - EXPENSE
            - INCOME
            - TRANSFER
            - REFUND
            - INVESTMENT
            - IOU
          example: 'EXPENSE'
          description: The type of transaction
        amount:
          type: number
          format: float
          example: 3.15
          description: The amount of the transaction
        account:
          $ref: '#/components/schemas/Account'
        description:
          type: string
          example: "Paypal"
          description: Transaction description
        tag:
          $ref: '#/components/schemas/AccountTag'
        created_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was created
        updated_at:
          type: string
          nullable: true
          format: date-time
          example: '2019-06-26T11:23:25.865677'
          description: The timestamp when the user was last modified/updated

    Transactions:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        balance:
          type: number
          format: float
          example: 3.15
          description: Transaction sum

paths:

  /users:
    post:
      summary: Creates an user
      operationId: balance_api.api.users.create_user
      description: Creates an user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    get:
      summary: Retrieves an user
      operationId: balance_api.api.users.me
      description: Retrieves an user
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


  /users/{user_id}/accounts:
    post:
      summary: Creates an user account
      operationId: balance_api.api.accounts.create_account
      description: Creates an user account
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

    get:
      summary: Lists all user accounts
      operationId: balance_api.api.accounts.list_accounts
      description: Lists all user accounts
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accounts'

  /users/{user_id}/accounts/{account_id}:
    get:
      summary: Retrieves an user account
      operationId: balance_api.api.accounts.find_account
      description: Retrieves an user account
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/AccountId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'


  /users/{user_id}/accounts/{account_id}/tags:
    get:
      summary: Retrieves the list of account tags for a user account
      operationId: balance_api.api.account_tags.list_account_tags
      description: Retrieves the list of account tags for a user account
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/AccountId'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTags'

  /users/{user_id}/transactions:
    post:
      summary: Creates a transaction
      operationId: balance_api.api.transactions.create_transaction
      description: Creates a transaction
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

    get:
      summary: Retrieves the list of transactions for a user
      operationId: balance_api.api.transactions.list_transactions
      description: Retrieves the list of transactions for a user
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/AccountIdQuery'
        - $ref: '#/components/parameters/PeriodType'
        - $ref: '#/components/parameters/PeriodOffset'
        - $ref: '#/components/parameters/StartDate'
        - $ref: '#/components/parameters/EndDate'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'

  /users/{user_id}/transactions/{transaction_id}:
    delete:
      summary: Deletes a single transaction
      operationId: balance_api.api.transactions.delete_transaction
      description: Deletes a single transaction for a given transaction_id
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TransactionId'
      responses:
        204:
          description: NO CONTENT


  /users/{user_id}/upload:
    post:
      summary: Uploads a file with several transactions
      operationId: balance_api.api.transactions.upload_transaction
      description: Uploads a file with several transactions
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                account_id:
                  type: string
                userId:
                  type: integer
                file:
                  type: string
                  format: binary
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
